version: '3.8'

services:
  # Serviço do Laravel (PHP + Nginx)
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    networks:
      - app_network
    depends_on:
      - db

  # Serviço do Nginx
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - app_network
    depends_on:
      - app

  # Serviço do MySQL
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_USER: ${DB_USERNAME:-laravel}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app_network

  # Serviço do Frontend (Vue.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - VITE_HOST=0.0.0.0
      - VITE_PORT=3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app_network
    command: npm run dev -- --host 0.0.0.0 --port 3000

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
    driver: local
